config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  get 'top/index'
  root to: 'top#index'

  # devise_for :users
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only:[:create, :index, :show, :edit, :update, :destroy]
  resources :users, only:[:index, :show, :edit, :update]
end

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <header>
      <div class="container clearfix">
        <nav class="navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="navbar-right clearfix">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id) do%>
                  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;&nbsp; Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path do%>
                  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;&nbsp; Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path do %>
                  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;&nbsp; Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp;&nbsp; logout
                <% end %>
              </li>
            <% else %>
              <li>
                <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;&nbsp;<a href="/">Home</a>
              </li>
              <li>
                <%= link_to "/home/about" do %>
                  <span class="glyphicon glyphicon-link" aria-hidden="true"></span>&nbsp;&nbsp; About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path do %>
                  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp;&nbsp; sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp;&nbsp; login
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <%= yield %>

    <footer>
       <div class="container">
         <div class="row">
          <div class="col-xs-6 col-xs-offset-6">
            <p style="margin-left: 400px;width: 500px;height: 50px;">CopyRight Infratop.inc</p>
          </div>
       </div>
      </div>
    </footer>
  </body>
</html>